apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managerdash-pvc
  namespace: "2401032"
  labels:
    app: managerdash
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
